{% set name = "vecstore" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PhilipJohnBasile/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: REPLACE_WITH_ACTUAL_SHA256

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - protobuf
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - vecstore-server --help

about:
  home: https://github.com/PhilipJohnBasile/vecstore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High-performance embeddable vector database
  description: |
    VecStore is a high-performance embeddable vector database with HNSW indexing,
    hybrid search capabilities, multi-language bindings, and comprehensive RAG toolkit.

    Features:
    - HNSW vector indexing with configurable parameters
    - Dense and sparse vector search
    - Hybrid search with multiple fusion strategies
    - Advanced metadata filtering
    - Multi-tenancy support
    - gRPC and HTTP servers
    - Python and JavaScript bindings

    Perfect for RAG (Retrieval-Augmented Generation) applications, semantic search,
    and machine learning workloads.
  doc_url: https://docs.rs/vecstore
  dev_url: https://github.com/PhilipJohnBasile/vecstore

extra:
  recipe-maintainers:
    - PhilipJohnBasile
